@startuml Viewpoint_AI-Core-ms1

' Force layout to left to right
left to right direction
package "Viewpoint AI Core" {
' Define classes with methods

class interfaceAPI <<FastAPI>>{
    +POST /rule
}

package "Utilities"
{

class RuleAnalyzer { 
    #rulePrompt: string  
    #jobId: string
    #ruleList: list[string]
    #compoundRule: bool
    +initialize(rulePrompt: String, jobId: String) -> void
    +checkBasic(rulePrompt: String) -> Boolean
    +checkCompound(rulePrompt: String) -> Boolean
    +breakdownCompound(rulePrompt: String) -> List
    +checkCapability(rule: String) -> Boolean
    +breakdownMonolithic(rule: String) -> Tuple
    +classifyPropmter(condition: String, prompt: String, classes: List) -> String
    +raiseExceptionToUser(message: String) -> void
    +putRuleInList(rule: String) -> void
    +returnRuleJsonList() -> json
}
}

}
note right of RuleAnalyzer : Handles the analysis and processing of rule prompts based on specific conditions.\nIt interacts with various APIs and manages the flow of data for rule validation and\ndecomposition.

' JSON Queries to the left of API
note left of interfaceAPI
  POST /rule JSON Query:
  {
    "job_id": "<GUID>",
    "prompt": "<string>"
  }
end note

' JSON Responses to the right of API
note right of interfaceAPI
  POST /rule JSON Response:
  {
    "job_id": "<GUID>",
    "prompt": "<string>",
    "rule_list": [
        {
            "prompt": "<string>",
            "conditional": {
                "choice": "<selection>",
                "parameters": {
                    "<parameter>": "<string>"
                }
            }
        }
    ]
  }
end note



@enduml
