# Use an official Tomcat base image with Java 17
FROM tomcat:9.0-jdk17-corretto

# Copy the WAR file into the Tomcat webapps directory
COPY structurizr-onpremises.war /usr/local/tomcat/webapps/

# Set the working directory to Tomcat's webapps directory
WORKDIR /usr/local/tomcat/webapps/

# Expose port 8080
EXPOSE 8080

# Command to run Tomcat
CMD ["catalina.sh", "run"]
